#!/bin/bash
# XV6 compile and run sricpt
# Will upload changes to files and fetch before starting
 
#Console colors!
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[1;34m'
ORANGE='\033[0;33m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'



printf "${GREEN}##################${NC}\n\n"
printf "${BLUE}Updating from Github!${NC}\n\n"

git fetch

printf "\n${BLUE}Done!${NC}\n\n"
printf "${GREEN}##################${NC}\n\n"

printf "${GREEN}##################${NC}\n\n"
printf "${BLUE}Staging new changes!${NC}\n\n"

git add -A
git status

printf "\n${BLUE}Done!${NC}\n\n"
printf "${GREEN}##################${NC}\n\n"

printf "${GREEN}##################${NC}\n\n"
printf "${BLUE}Commiting to git!${NC}\n\n"

git commit -m "Compile Update"
git push

printf "\n${BLUE}Done!${NC}\n\n"
printf "${GREEN}##################${NC}\n\n"


printf "${GREEN}##################${NC}\n\n"
printf "${BLUE}Starting XV6!${NC}\n\n"
printf "${GREEN}##################${NC}\n\n"

make clean
make qemu





