#!/bin/bash
# XV6 compile and run sricpt
# Will upload changes to files and fetch before starting

echo "##############\nUpdating from git!"
git fetch
echo "Staging new changes!"
git add -A
git status
echo "Commiting to git!"
git commit -m "Testing"

